In [1]:
import psycopg2
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# Connect to the PostgreSQL database
conn = psycopg2.connect(
    dbname="sih_db",
    user="parag",
    host="localhost",
    port="5432"
)
print("Connected to database successfully!")

Connected to database successfully!

### Table: `DISEASES`

In [2]:
pd.read_sql_query('SELECT * FROM diseases LIMIT 3;', conn)

,disease_id,disease_name,description
0,1,African Swine Fever,Highly contagious viral hemorrhagic disease ca...
1,2,Anthrax,Bacterial disease caused by Bacillus anthracis.
2,3,Avian Influenza,Viral disease caused by Influenza A virus (Ort...

### Table: `FIELD_REPORTS`

In [3]:
pd.read_sql_query('SELECT * FROM field_reports LIMIT 3;', conn)

,report_id,farmer_id,animal_species,photo_url,symptom_ids,latitude,longitude,reported_at
0,1,388,Cats,s3://livestock-images-prod/mock_image_1.jpg,"[28, 51, 9, 52]",-15.170741,-123.853220,2026-09-02 21:43:07.537208
1,2,308,Horses,s3://livestock-images-prod/mock_image_2.jpg,[59],-75.775903,-33.936730,2026-09-02 21:43:07.537208
2,3,274,Warthogs,s3://livestock-images-prod/mock_image_3.jpg,"[62, 58]",23.408952,-140.530772,2026-09-02 21:43:07.537208

### Table: `LAB_REPORTS`

In [4]:
pd.read_sql_query('SELECT * FROM lab_reports LIMIT 3;', conn)

,lab_report_id,report_id,lab_technician_id,confirmed_disease_id,test_method,test_results,is_final_truth,used_in_training,verified_at
0,1,9,566,9,Blood Culture,Confirmed positive via laboratory diagnostics ...,True,False,2026-09-02 21:43:07.537208
1,2,10,567,8,Blood Culture,Confirmed positive via laboratory diagnostics ...,True,False,2026-09-02 21:43:07.537208
2,3,11,567,1,Blood Culture,Confirmed positive via laboratory diagnostics ...,True,False,2026-09-02 21:43:07.537208

### Table: `MODEL_VERSIONS`

In [5]:
pd.read_sql_query('SELECT * FROM model_versions LIMIT 3;', conn)

,model_version_id,model_type,version_name,model_path,dataset_version,accuracy,precision_score,recall_score,f1_score,trained_at,deployed_at,is_active
0,1,symptom_tabular,RF_v1_base,s3://models/rf_v1.pkl,None,0.85,None,None,None,2026-09-02 21:43:07.537208,None,True
1,2,image,CNN_v1_base,s3://models/cnn_v1.pth,None,0.88,None,None,None,2026-09-02 21:43:07.537208,None,True
2,3,multimodal,Ensemble_v1_base,s3://models/ensemble_v1.pkl,None,0.92,None,None,None,2026-09-02 21:43:07.537208,None,True

### Table: `PREDEFINED_SYMPTOM_MAP`

In [6]:
pd.read_sql_query('SELECT * FROM predefined_symptom_map LIMIT 3;', conn)

,map_id,symptom_id,disease_id,species_id,symptom_weight,is_pathognomonic
0,1,35,11,1,0.7,False
1,2,47,11,1,0.6,False
2,3,62,11,1,0.9,True

### Table: `SPECIES`

In [7]:
pd.read_sql_query('SELECT * FROM species LIMIT 3;', conn)

   species_id species_name
0           1       Cattle
1           2        Sheep
2           3        Goats

### Table: `SYMPTOMS`

In [8]:
pd.read_sql_query('SELECT * FROM symptoms LIMIT 3;', conn)

   symptom_id        symptom_name description
0           1          High fever        None
1           2    Loss of appetite        None
2           3  Skin discoloration        None

### Table: `TRIAGE_RESULTS`

In [9]:
pd.read_sql_query('SELECT * FROM triage_results LIMIT 3;', conn)

,triage_id,report_id,symptom_model_version_id,image_model_version_id,multimodal_model_version_id,symptom_prediction_id,symptom_confidence,image_prediction_id,image_confidence,final_prediction_id,final_confidence,risk_score,risk_level,processing_method,created_at
0,1,1,1,2,3,6,0.7898,6,0.6651,6,0.7060,0.7806,MEDIUM,None,2026-09-02 21:43:07.537208
1,2,2,1,2,3,9,0.6449,9,0.5410,9,0.6668,0.6316,MEDIUM,None,2026-09-02 21:43:07.537208
2,3,3,1,2,3,1,0.8718,1,0.8908,1,0.8184,0.6506,HIGH,None,2026-09-02 21:43:07.537208

### Table: `USERS`

In [10]:
pd.read_sql_query('SELECT * FROM users LIMIT 3;', conn)

   user_id  username    role
0        1  farmer_1  Farmer
1        2  farmer_2  Farmer
2        3  farmer_3  Farmer

### Table: `VET_VERIFICATIONS`

In [11]:
pd.read_sql_query('SELECT * FROM vet_verifications LIMIT 3;', conn)

,verification_id,report_id,vet_id,confirmed_disease_id,is_confirmed,clinical_notes,internal_hemorrhage,used_in_training,verified_at
0,1,2,547,9,True,Mock clinical notes evaluating symptoms and im...,None,False,2026-09-02 21:43:07.537208
1,2,4,501,7,True,Mock clinical notes evaluating symptoms and im...,None,False,2026-09-02 21:43:07.537208
2,3,6,522,9,True,Mock clinical notes evaluating symptoms and im...,None,False,2026-09-02 21:43:07.537208